### ISSUE TITLE
VerifyError caused by invokeinterface with long/double parameters

### ISSUE THREAD

**Issue by shoaniki** [cojen/Maker#3]
The following example code throws a VerifyError that I don't _think_ is my fault:
```java
public class Main {
    public interface Foo {
        double bar(DoubleBinaryOperator op);
    }

    public static void main(String[] args) throws Exception {
        var c = ClassMaker.begin().implement(Foo.class);
        var m = c.addMethod(double.class, "bar", DoubleBinaryOperator.class);
        m.return_(m.param(0).invoke("applyAsDouble", 2.0, 4.5));
        System.out.println(((Foo) c.finish().getConstructor().newInstance()).bar(Double::sum));
    }
}
```
The error message is
```
Exception in thread "main" java.lang.VerifyError: Inconsistent args count operand in invokeinterface
Exception Details:
  Location:
    org/cojen/maker/ClassMaker-3.bar(Ljava/util/function/DoubleBinaryOperator;)D @7: invokeinterface
  Reason:
    Error exists in the bytecode
  Bytecode:
    0000000: 2b14 0010 1400 12b9 000c 0400 af       
```
The bytecode in question is
```
 0: aload_1
 1: ldc2_w        #16         // double 2.0d
 4: ldc2_w        #18         // double 4.5d
 7: invokeinterface #12,  4   // InterfaceMethod java/util/function/DoubleBinaryOperator.applyAsDouble:(DD)D
12: dreturn
```
And indeed we see that the invokeinterface claims to use 4 stack elements, but requires 5.

I think the cause may be at https://github.com/cojen/Maker/blob/e8d62f313be55637354b3e0ad69ae807c4d67fb6/src/main/java/org/cojen/maker/TheMethodMaker.java#L754
It looks as though this array doesn't contain the receiver type, so it probably shouldn't be skipping the first parameter?

**Comment by broneill** [comment]
Thanks for the report and initial investigation. I'll take a look at this further.

**Comment by broneill** [comment]
Let me know if this fix works for you: https://github.com/cojen/Maker/commit/53be6ff83e942046cf6511e652f71831d0343a83

**Comment by shoaniki** [comment]
Yes, that works perfectly, thank you!

This is a beautiful library btw. I've tried a bunch of code generation libraries over the years and all the others felt like more trouble than they were worth, but this one gets it right -- thank you for writing it :)
