### ISSUE TITLE
What about imports?

### ISSUE THREAD

**Issue by Osiris-Team** [cojen/Maker#7]
How are imports handled? Automatically or do I have to add them manually? If so where/how do I do that?

**Comment by Osiris-Team** [comment]
If I want to create a method that returns a list for example, I would need to add `import java.util.List;` to the top of the file/class.

**Comment by broneill** [comment]
Such an import statement would only exist in the code that's making the the generated class, but not in the generated class itself.

```java
import java.util.ArrayList;
import java.util.List;
...

public class Generator {
    public static Class<?> makeClass() {
        ClassMaker cm = ClassMaker.begin().public_();
        MethodMaker mm = cm.addMethod(List.class, "doSomething").public_().static_();
        mm.return_(mm.new_(ArrayList.class));
        return cm.finish();
    }
}
```

**Comment by Osiris-Team** [comment]
What if I do this:
```java
MethodMaker mm = cm.addMethod("List<Object>" etc...
```
aka there is no import of List in the current file.

**Comment by broneill** [comment]
You need to use the fully qualified name if you're specifying classes with strings.

```java
public class Generator {
    public static void main(String[] args) throws Exception {
        System.out.println(makeClass());
    }

    public static Class<?> makeClass() {
        ClassMaker cm = ClassMaker.begin().public_();
        MethodMaker mm = cm.addMethod("java.util.List", "doSomething").public_().static_();
        mm.return_(mm.new_("java.util.ArrayList"));
        return cm.finish();
    }
}
```

Also note that generics aren't supported. If you try to use `<Object>` in the class name, you end up with a confusing exception.

**Comment by Osiris-Team** [comment]
Ok thx
